name: Build Psych Extended + Release
run-name: Psych Extended V1.0.2 PreRelease
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: PsychExtended
  REPO_PATH: 28AloneDark53/Psych-Extended

jobs:
  get-commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.COMMIT_HASH }}
    steps:
      - name: Check Repository
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "REPO_PATH: ${{ env.REPO_PATH }}"
          if [[ "$GITHUB_REPOSITORY" != "${{ env.REPO_PATH }}" ]]; then
            echo "Doesn't seem to be correct, returning SIGABRT..."
            exit 6
          else
            echo "Seems to be correct..."
          fi

      - name: Get latest commit hash
        id: get_commit_hash
        run: |
          commit_hash=${GITHUB_SHA::7}
          echo "Latest commit hash is $commit_hash"
          echo "::set-output name=COMMIT_HASH::$commit_hash"

  build:
    name: ${{ matrix.name }}
    needs: get-commit-hash
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            setupCommand: .\"setup/windows.bat"
            artifactName: windowsBuild-x86_64
            artifactPath: export\release\windows\bin\*
            system: Windows
          - name: Android-Arm64
            os: ubuntu-24.04
            buildArgs: "android -ONLY_ARM64 -final"
            setupCommand: sh ./setup/mobile.sh
            artifactName: androidBuild-Arm64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: Android-Armv7
            os: ubuntu-24.04
            buildArgs: "android -ONLY_ARMV7 -final"
            setupCommand: sh ./setup/mobile.sh
            artifactName: androidBuild-Armv7
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: Android-Debug
            os: ubuntu-24.04
            buildArgs: "android -ONLY_ARM64 -final"
            setupCommand: sh ./setup/mobile.sh
            artifactName: androidBuild-Debug
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        setupCommand: ${{ matrix.setupCommand }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        system: ${{ matrix.system }}

  Releaser:
    needs: [get-commit-hash, build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Arm64 Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-Arm64
           path: /home/runner

      - name: Move Arm64 Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-1.0.2-PreRelease-(Arm64).apk
        
      - name: Download Armv7 Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-Armv7
           path: /home/runner

      - name: Move Armv7 Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-1.0.2-PreRelease-(Armv7).apk
        
      - name: Download Windows Build
        uses: actions/download-artifact@main
        with:
           name: windowsBuild
           path: /home/runner

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DevBuild ${{ needs.get-commit-hash.outputs.commit_hash }}"
          tag_name: "devbuild-${{ needs.get-commit-hash.outputs.commit_hash }}"
          prerelease: true
          files: |
            /home/runner/*.apk
            /home/runner/*.zip
            /home/runner/*.tar